name: .NET Core CI

on: [push]

env:
  AZURE_WEBAPP_NAME: bmi202620260924172211    # Set this to your application's name
  #AZURE_WEBAPP_PACKAGE_PATH: '.'              # Set this to the path to your web app project, defaults to the repository root
  #AZURE_WEBAPP_PACKAGE_PATH: '../../WebApplicationTestAzureGitHubDotNET10' # putting wwwroot here doesn't work. try down below.
  #AZURE_WEBAPP_PACKAGE_PATH: "WebApplicationTestAzureGitHubDotNET10/WebApplicationTestAzureGitHubDotNET10.csproj"
  #AZURE_WEBAPP_PACKAGE_PATH: '../../'
  AZURE_WEBAPP_PACKAGE_PATH: WebApplicationTestAzureGitHubDotNET10\published
  WORKING_DIRECTORY: WebApplicationTestAzureGitHubDotNET10
  DOTNET_VERSION: '10.0.x'                    # Set this to the dot net version to use

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Check out the repo
      - uses: actions/checkout@main
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          # dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' # still has /myapp in it.
          #dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
          #dotnet publish -c Release --property:PublishDir='./publish'
          dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          #package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
          #package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/wwwroot'
          #package: './publish'
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
